shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/website/urls.py
from django.urls import path
from .views import CreateNote, NotesView, DltNote, ShowNote, RegisterUser, LoginUser, logout_user, UserProfile

app_name = 'website'
urlpatterns = [
    path('', NotesView.as_view(), name='index'),
    path('create_note', CreateNote.as_view(), name='create-note'),
    path('note/<int:pk>/delete/', DltNote.as_view(), name='delete-note'),
    path('note/<int:pk>', ShowNote.as_view(), name='show-note'),
    path('register', RegisterUser.as_view(), name='register'),
    path('login', LoginUser.as_view(), name='login'),
    path('logout', logout_user, name='logout'),
    path('user_profile',  UserProfile.as_view(), name='user-profile'),
]

shop/website/models.py
from datetime import datetime

from django.core.validators import MinLengthValidator
from django.urls import reverse
from django.db import models


# Create your models here.
class NoteModel(models.Model):
    author = models.CharField('author', max_length=30, validators=[MinLengthValidator(5, 'Minimum 5 characters required')])
    title = models.CharField('title', max_length=30)
    category = models.CharField('category', max_length=30)
    abstract = models.CharField('abstract', max_length=300,
                                validators=[MinLengthValidator(10, 'Abstract should contain a minimum of 10 characters')])
    text = models.TextField('text', validators=[MinLengthValidator(25, 'Note main text should contain a minimum of 25 characters')])
    publish_date = models.DateTimeField('publish date', default=datetime.now())
    is_published = models.BooleanField('is published?', default=True)

    def get_absolute_url(self):
        return reverse('website:create_note', kwargs={'id': self.pk})

    def __str__(self):
        return str(self.title) + ' - ' + str(self.publish_date)

shop/website/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.forms import ModelForm, TextInput, PasswordInput, CharField, Textarea

from .models import NoteModel


class NoteForm(ModelForm):
    class Meta:
        model = NoteModel
        fields = ['author', 'title', 'category', 'abstract', 'text']
        widgets = {
            'author': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'author',
                'id': 'floatingInput',
            }),
            'title': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'title',
                'id': 'floatingInput'
            }),
            'category': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'category',
                'id': 'floatingInput'
            }),
            'abstract': Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'text',
                'id': 'floatingTextarea1',
                "rows": 5, "cols": 20,
            }),
            'text': Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'text',
                'id': 'floatingTextarea1',
                "rows": 10, "cols": 20,
            }),
        }

    def clean(self):
        # data from the form is fetched using super function
        cleaned_data = super().clean()

        # extract the author and text field from the data
        author = self.cleaned_data.get('author')
        abstract = self.cleaned_data.get('abstract')
        text = self.cleaned_data.get('text')

        # conditions
        if len(author) < 5:
            self.add_error('author', 'Minimum 5 characters required')

        if len(abstract) < 10:
            self.add_error('abstract', 'Minimum 10 characters required')

        if len(text) < 25:
            self.add_error('text', 'Note main text should contain a minimum of 25 characters')

        return cleaned_data


class RegisterUserForm(UserCreationForm):
    username = CharField(label='Login', widget=TextInput(attrs={'class': 'form-control', 'placeholder': 'Login', 'id': 'login-input'}))
    password1 = CharField(label='Password', widget=PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password', 'id': 'password1-input'}))
    password2 = CharField(label='Password confirmation', widget=PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password confirmation', 'id': 'password2-input'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.label_suffix = ''

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']


class LoginUserForm(AuthenticationForm):
    username = CharField(label='Login', widget=TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Login', 'id': 'login-input'}
    ))

    password = CharField(label='Password', widget=PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Password', 'id': 'password-input'}
    ))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.label_suffix = ''

    class Meta:
        model = User
        fields = ['username', 'password']

shop/website/views.py
from django.contrib.auth import logout
# from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DeleteView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User

# from . import services
from .forms import NoteForm, RegisterUserForm, LoginUserForm
from .models import NoteModel
from .utils import DataMixin


class NotesView(ListView):
    model = NoteModel
    template_name = 'website/index.html'
    context_object_name = 'notes'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Main'
        return context

    def get_queryset(self):
        return NoteModel.objects.filter(is_published=True)


class CreateNote(LoginRequiredMixin, DataMixin, CreateView):
    form_class = NoteForm
    template_name = 'website/create_note.html'
    success_message = 'Note successfully created!'
    error_message = 'Error saving the Note, check fields below.'
    login_url = reverse_lazy('website:index')
    success_url = reverse_lazy('website:create-note')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['notes'] = NoteModel.objects.all()
        return context


class DltNote(DeleteView):
    model = NoteModel
    success_url = '/create_note'

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


class ShowNote(DetailView):
    model = NoteModel
    template_name = 'website/show_note.html'
    pk_url_kwarg = 'pk'
    context_object_name = 'note'


class RegisterUser(DataMixin, CreateView):
    form_class = RegisterUserForm
    template_name = 'website/register.html'
    success_url = reverse_lazy('website:index')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context |= self.get_user_context(title='Registration')
        return context


class LoginUser(DataMixin, LoginView):
    form_class = LoginUserForm
    template_name = 'website/login.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context |= self.get_user_context(title='Enter')
        return context

    def get_success_url(self):
        return reverse_lazy('website:index')


def logout_user(request):
    logout(request)
    return redirect('website:index')


class UserProfile(ListView):
    template_name = 'website/user_profile.html'
    model = User
    context_object_name = 'account'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'User profile'
        return context

    def get_queryset(self):
        # Choices are: date_joined, email, first_name, groups, id, is_active, is_staff, is_superuser,
        # last_login, last_name, logentry, password, user_permissions, username
        return User.objects.filter(username=self.request.user).values()

shop/website/templates/website/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        {% block title %}

        {% endblock %}

        {% load static %}

        <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap-grid.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css.map' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.min.css.map' %}">
        <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    </head>

    <body>
        <div class="container py-3">
            <header>
                <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">

                    <nav class="d-inline-flex">
                        <a class="me-3 py-2 text-dark text-decoration-none" href="/"><strong class="navbar-brand">Main</strong></a>
                        {% if request.user.is_authenticated %}
                            <a href="{% url 'website:user-profile' %}" class="navbar-brand d-flex align-items-center text-dark text-decoration-none"><strong>User profile</strong></a>
                            <a class="me-3 py-2 text-dark text-decoration-none navbar-brand" href="/create_note"><strong>Create note</strong></a>
                        {% endif %}
                    </nav>

                    <div class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
                        {% if request.user.is_authenticated %}
                            <a href="{% url 'website:user-profile' %}" class="navbar-brand d-flex align-items-center text-dark text-decoration-none"><strong>User profile</strong></a>
                            <strong class="navbar-brand d-flex align-items-center">{{ user.username }}  |  </strong>
                            <a href="{% url 'website:logout' %}" class="navbar-brand d-flex align-items-center text-dark text-decoration-none"><strong>Logout</strong></a>
                        {% else %}
                            <a href="{% url 'website:register' %}" class="navbar-brand d-flex align-items-center text-dark text-decoration-none"><strong>Registration</strong></a>
                            <strong class="navbar-brand">  |  </strong>
                            <a href="{% url 'website:login' %}" class="navbar-brand d-flex align-items-center text-dark text-decoration-none"><strong>Login</strong></a>
                        {% endif %}
                    </div>

                </div>
            </header>
        </div>

        {% block body %}

        {% endblock %}

        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/jquery.min.js' %}"></script>
<!--        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>-->
    </body>
</html>

shop/website/templates/website/create_account.html
{% extends 'website/base.html' %}

{% block title %}
    <title>Create account</title>
{% endblock %}

{% block body %}
    <main>
        <div class="container">
            <form method="POST">
            {% csrf_token %}

                <h1>Create account</h1>

                {% for el in form %}
                <div class="form-floating mb-3">
                    <label for="floatingInput">{{ el.label }}:</label>
                    {{ el }}
                </div>

                {% endfor %}

                <button type="submit" class="btn btn-primary">Create new account</button>
            </form>
            <h3>{{ error }}</h3>
        </div>>
    </main>
{% endblock %}

shop/website/templates/website/create_note.html
{% extends 'website/base.html' %}

{% block title %}
    <title>Create note</title>
{% endblock %}

{% block body %}
    <main>

        <div class="container">
            <div class="form">
                <form method="POST" autocomplete="off" enctype="multipart/form-data">
                {% csrf_token %}
                    <div class="heading">
                        <h1>Create note</h1>
                    </div>
                    {% for el in form %}
                    <div class="mb-3">

                        <div class="form-floating">
                            {{ el }}
                            {{ el.label_tag }}
                            {% if el.errors %}
                                    <ul>
                                        {% for error in el.errors %}
                                            <li>
                                                <span class="error-span">{{ error }}</span>
                                            </li>
                                        {% endfor %}
                                    </ul>
                            {% endif %}
                        </div>

                    </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-success">Create new note</button>

                </form>
            </div>

            {% if notes %}

                <div class="caption">
                    <h4>Notes</h4>
                </div>

                {% for note in notes %}

                    <div class="tables">

                        <table class="table table-borderless" style="width:100%">
                            <colgroup>
                               <col style="width: 10%;">
                               <col style="width: 25%;">
                               <col style="width: 30%;">
                               <col style="width: 15%;">
                               <col style="width: 20%;">
                            </colgroup>
                            <thead class="table-dark">
                                <tr>
                                <th scope="col">id</th>
                                <th scope="col">author</th>
                                <th scope="col">title</th>
                                <th scope="col">category</th>
                                <th scope="col">publish date</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr class="bordered">
                                    <td><span style="color:green"><b>{{ note.id }}</b></span></td>
                                    <td><b>{{ note.author }}</b></td>
                                    <td><b>{{ note.title }}</b></td>
                                    <td><b>{{ note.category }}</b></td>
                                    <td><b>{{ note.publish_date }}</b></td>
                                </tr>
                            </tbody>
                        </table>

                        <table>
                            <colgroup>
                               <col style="width: 10%;">
                               <col style="width: 80%;">
                            </colgroup>
                            <thead></thead>
                            <tbody>
                                <tr class="align-top">
                                    <td>
                                        <b>Abstract: </b>
                                    </td>
                                    <td>
                                        {{ note.abstract }}
                                    </td>
                                </tr>

                                <tr class="align-top">
                                    <td>
                                        <b>Text: </b>
                                    </td>
                                    <td>
                                        {{ note.text }}
                                    </td>
                                </tr>
                            </tbody>
                        </table>

                        <div class="d-flex justify-content-between">
                            <div class="read-note-href">
                                <a href="{% url 'website:delete-note' note.pk %}" class="btn btn-close" title="delete"></a>
                            </div>
                            <div class="read-note-href">
                                {% if note.is_published %}
                                    <p>Is published: <span class="is-published">{{ note.is_published }}.</span></p>
                                {% else %}
                                    <p>Is published: <span class="error-span">{{ note.is_published }}.</span></p>
                                {% endif %}</div>
                            <div class="read-note-href" align="right">
                                <a href="{% url 'website:show-note' note.pk %}" title="read note" class="link-success">Read note</a>
                            </div>
                        </div>

                    </div>

                {% endfor %}
            {% endif %}
        </div>>
    </main>
{% endblock %}

shop/website/templates/website/index.html
{% extends 'website/base.html' %}

{% block title %}
    <title>{{ title }}</title>
{% endblock %}

{% block body %}
    <main>
        <div class="container">

            {% if notes %}

                <div class="caption">
                    <h4>Notes</h4>
                </div>

                {% for note in notes %}

                    <div class="tables">

                        <table class="table table-borderless" style="width:100%">
                            <colgroup>
                               <col style="width: 10%;">
                               <col style="width: 25%;">
                               <col style="width: 30%;">
                               <col style="width: 15%;">
                               <col style="width: 20%;">
                            </colgroup>
                            <thead class="table-dark">
                                <tr>
                                <th scope="col">id</th>
                                <th scope="col">author</th>
                                <th scope="col">title</th>
                                <th scope="col">category</th>
                                <th scope="col">publish date</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr class="bordered">
                                    <td><span style="color:green"><b>{{ note.id }}</b></span></td>
                                    <td><b>{{ note.author }}</b></td>
                                    <td><b>{{ note.title }}</b></td>
                                    <td><b>{{ note.category }}</b></td>
                                    <td><b>{{ note.publish_date }}</b></td>
                                </tr>
                            </tbody>
                        </table>

                        <table>
                            <colgroup>
                               <col style="width: 15%;">
                               <col style="width: 85%;">
                            </colgroup>
                            <thead></thead>
                            <tbody>
                                <tr class="align-top">
                                    <td>
                                        <b>Abstract: </b>
                                    </td>
                                    <td>
                                        {{ note.abstract }}
                                    </td>
                                </tr>

                                <tr class="align-top">
                                    <td>
                                        <b>Text: </b>
                                    </td>
                                    <td>
                                        {{ note.text }}
                                    </td>
                                </tr>
                            </tbody>
                        </table>

                    </div>

                {% endfor %}
            {% else %}
                <div class="caption">
                    <h4>There is no any note here.</h4>
                </div>
            {% endif %}

        </div>
    </main>
{% endblock %}

shop/website/templates/website/login.html
{% extends 'website/base.html' %}

{% block title %}
<title>{{ title }}</title>
{% endblock %}

{% block body %}
    <form class="form-signin d-flex justify-content-center" method="post">
        <div class="d-flex flex-column align-items-center w-100">
            <h1 class="h3 mb-3 font-weight-normal">Enter</h1>
            {% csrf_token %}
            {% for el in form %}
            <div class="mb-3">

                <div class="form-floating">
                    {{ el }}
                    {{ el.label_tag }}
                    {% if el.errors %}
                    <ul>
                        {% for error in el.errors %}
                        <li><strong class="text-danger">{{ error }}</strong></li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>

            </div>
            {% endfor %}

            <button type="submit" class="btn btn-success">Enter</button>
        </div>
    </form>
{% endblock %}

shop/website/templates/website/register.html
{% extends 'website/base.html' %}

{% block title %}
    <title>{{ title }}</title>
{% endblock %}

{% block body %}
    <form class="form-signin d-flex justify-content-center" method="post">
        <div class="d-flex flex-column align-items-center w-100">
            <h1 class="h3 mb-3 font-weight-normal">Registration</h1>
            {% csrf_token %}
            {% for el in form %}
            <div class="mb-3">

                <div class="form-floating">
                    {{ el }}
                    {{ el.label_tag }}
                    {% if el.errors %}
                    <ul>
                        {% for error in el.errors %}
                        <li><strong class="text-danger">{{ error }}</strong></li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>

            </div>
            {% endfor %}

            <button type="submit" class="btn btn-success">Register</button>
        </div>
    </form>

{% endblock %}

shop/website/templates/website/show_note.html
{% extends 'website/base.html' %}

{% block title %}
    <title>{{ title }}</title>
{% endblock %}

{% block body %}
<div class="container">
<!--    <p>{{ note.author }}</p>-->
<!--    <p>{{ note.title }}</p>-->
<!--    <p>{{ note.category }}</p>-->
<!--    <p>{{ note.is_published }}</p>-->
<!--    <p>{{ note.publish_date }}</p>-->
<!--    <p>{{ note.abstract }}</p>-->
<!--    <p>{{ note.text }}</p>-->

    <div class="caption">
        <h4>{{ note.title }}</h4>
    </div>

    <div class="tables">

        <table class="table table-borderless" style="width:100%">
            <colgroup>
               <col style="width: 10%;">
               <col style="width: 25%;">
               <col style="width: 30%;">
               <col style="width: 15%;">
               <col style="width: 20%;">
            </colgroup>
            <thead class="table-dark">
                <tr>
                <th scope="col">id</th>
                <th scope="col">author</th>
                <th scope="col">title</th>
                <th scope="col">category</th>
                <th scope="col">publish date</th>
                </tr>
            </thead>
            <tbody>
                <tr class="bordered">
                    <td><span style="color:green"><b>{{ note.id }}</b></span></td>
                    <td><b>{{ note.author }}</b></td>
                    <td><b>{{ note.title }}</b></td>
                    <td><b>{{ note.category }}</b></td>
                    <td><b>{{ note.publish_date }}</b></td>
                </tr>
            </tbody>
        </table>

        <table>
            <colgroup>
               <col style="width: 10%;">
               <col style="width: 80%;">
            </colgroup>
            <thead></thead>
            <tbody>
                <tr class="align-top">
                    <td>
                        <b>Abstract: </b>
                    </td>
                    <td>
                        {{ note.abstract }}
                    </td>
                </tr>

                <tr class="align-top">
                    <td>
                        <b>Text: </b>
                    </td>
                    <td>
                        {{ note.text }}
                    </td>
                </tr>
            </tbody>
        </table>

        <div class="d-flex justify-content-between">
            <div class="read-note-href">
                <a href="{% url 'website:delete-note' note.pk %}" class="btn btn-close" title="delete"></a>
            </div>
            <div class="read-note-href">
                {% if note.is_published %}
                    <p>Is published: <span class="is-published">{{ note.is_published }}.</span></p>
                {% else %}
                    <p>Is published: <span class="error-span">{{ note.is_published }}.</span></p>
                {% endif %}
            </div>
        </div>

    </div>


</div>

{% endblock %}

shop/website/templates/website/user_profile.html
{% extends 'website/base.html' %}

{% block title %}
<title>{{ title }}</title>
{% endblock %}

{% block body %}
    <div class="container">
        <div class="d-flex">
            <div class="mb3">
                <div class="heading">
                    <h1>Account: {{ user.username }}</h1>
                </div>
                <div>
                    <table class="table table-striped table-hover">
                        {% for data in account %}
                            {% for key, value in data.items %}
                                <tr>
                                    <td>{{ key }}</td>
                                    <td>{{ value }}</td>
                                </tr>
                            {% endfor %}
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}